export type Language = "en" | "ru";

export const messages = {
  en: {
    "nav.tools":"Tools","nav.explore":"Explore","nav.lab":"Lab","nav.library":"Library","nav.about":"About","nav.contact":"Contact",
    "common.open":"Open","common.copy":"Copy","common.copied":"Copied to clipboard","common.copyFailed":"Copy failed — select the text manually","common.save":"Save","common.saved":"Project saved","common.remix":"Remix","common.delete":"Delete","common.duplicate":"Duplicate","common.rename":"Rename","common.search":"Search","common.all":"All","common.settings":"Settings","common.close":"Close","common.next":"Next","common.skip":"Skip","common.back":"Back","common.randomized":"Randomized","common.fullscreen":"Fullscreen",
    "shell.launch":"Launch Lab","shell.created":"Created by","shell.version":"NEXUS LAB // v3.0","shell.online":"System online",
    "home.label":"Creative system / v2.0","home.title":"WHAT DO YOU WANT TO CREATE?","home.placeholder":"Describe your idea...","home.hint":"Describe a prompt, palette, gradient, neon style or interface idea.","home.suggest":"Suggested system","home.open":"Open suggested lab","home.quick":"Quick start","home.recent":"Recently used","home.creator":"About the creator","home.creatorText":"18-year-old frontend developer and student at the College of Digital Technologies, creating modern interactive websites and experimenting with design, motion and frontend technologies.","home.more":"More about me",
    "library.title":"MY LIBRARY","library.subtitle":"Every saved experiment, ready to open, copy or remix.","library.empty":"YOUR LIBRARY IS EMPTY","library.emptyHint":"Create your first experiment and save it to the system.","library.favorites":"Favorites","library.search":"Search saved systems...","library.renamed":"Project renamed","library.deleted":"Project deleted","library.duplicated":"Project duplicated",
    "explore.title":"EXPLORE THE SIGNAL.","explore.subtitle":"Curated digital experiments. Search, filter, open and remix.","explore.trending":"Trending","explore.new":"New","explore.colors":"Colors","explore.gradients":"Gradients","explore.prompts":"Prompts","explore.motion":"Motion","explore.neon":"Neon","explore.noResults":"No signals match this search.",
    "about.label":"ABOUT THE CREATOR","about.hero":"ARSENII PIANKOV","about.roles":"18 YEARS OLD • FRONTEND DEVELOPER • STUDENT • CREATIVE DEVELOPER","about.hello":"HI, I'M ARSENII.","about.body1":"I'm an 18-year-old student at the College of Digital Technologies, currently studying frontend development and building modern websites.","about.body2":"I'm especially interested in the point where development meets design, motion and interaction. I enjoy creating websites that are functional, visually memorable and enjoyable to use.","about.body3":"NEXUS LAB is one of my personal projects where I combine development, design, experimentation and useful digital tools inside one interactive experience.","about.what":"WHAT I DO","about.stack":"CURRENT STACK","about.philosophy":"I DON'T JUST WANT TO BUILD PAGES. I WANT TO BUILD EXPERIENCES.","about.github":"Some of my frontend projects, experiments and code can be found on GitHub.","about.viewGithub":"View GitHub",
    "contact.label":"HAVE A PROJECT OR AN IDEA?","contact.hero":"LET'S CREATE SOMETHING.","contact.role":"Frontend Developer • Student at College of Digital Technologies","contact.email":"Email","contact.telegram":"Telegram","contact.github":"GitHub","contact.discord":"Discord","contact.instagram":"Instagram","contact.vk":"VK","contact.copyDiscord":"Copy username","contact.discordCopied":"Discord username copied","contact.final":"LET'S BUILD SOMETHING DIFFERENT.","contact.available":"Open to projects and collaborations","contact.send":"Send email",
    "settings.title":"NEXUS SETTINGS","settings.appearance":"Appearance","settings.language":"Language","settings.motion":"Motion","settings.dark":"Dark","settings.light":"Light","settings.system":"System","settings.full":"Full","settings.reduced":"Reduced","settings.off":"Off","settings.english":"English","settings.russian":"Русский",
    "commands.title":"COMMAND PALETTE","commands.placeholder":"Search commands...","commands.empty":"No command found","commands.openTools":"Open Tool Hub","commands.openPrompt":"Open Prompt Lab","commands.openGradient":"Open Gradient Lab","commands.openColors":"Open Color Lab","commands.openNeon":"Open Neon Lab","commands.openMotion":"Open Motion Lab","commands.openLibrary":"Open My Library","commands.openGithub":"Open GitHub","commands.openTelegram":"Open Telegram","commands.copyDiscord":"Copy Discord","commands.sendEmail":"Send email","commands.light":"Switch to light mode","commands.dark":"Switch to dark mode","commands.language":"Change language",
    "onboarding.one":"CHOOSE A TOOL","onboarding.oneText":"Start from Quick Start, Tool Hub or the command palette.","onboarding.two":"CREATE SOMETHING","onboarding.twoText":"Every control updates a live preview instantly.","onboarding.three":"SAVE OR REMIX","onboarding.threeText":"Keep results in your local Library and return anytime.",
    "changelog.title":"CHANGELOG","changelog.subtitle":"A living record of NEXUS LAB evolution.","notFound.title":"SIGNAL LOST","notFound.action":"Return to Nexus"
  },
  ru: {
    "nav.tools":"Инструменты","nav.explore":"Explore","nav.lab":"Lab","nav.library":"Библиотека","nav.about":"Обо мне","nav.contact":"Контакты",
    "common.open":"Открыть","common.copy":"Копировать","common.copied":"Скопировано","common.copyFailed":"Ошибка копирования — выделите текст вручную","common.save":"Сохранить","common.saved":"Проект сохранён","common.remix":"Ремикс","common.delete":"Удалить","common.duplicate":"Дублировать","common.rename":"Переименовать","common.search":"Поиск","common.all":"Все","common.settings":"Настройки","common.close":"Закрыть","common.next":"Далее","common.skip":"Пропустить","common.back":"Назад","common.randomized":"Обновлено","common.fullscreen":"На весь экран",
    "shell.launch":"Открыть Lab","shell.created":"Создано","shell.version":"NEXUS LAB // v3.0","shell.online":"Система активна",
    "home.label":"Креативная система / v2.0","home.title":"ЧТО ТЫ ХОЧЕШЬ СОЗДАТЬ?","home.placeholder":"Опиши свою идею...","home.hint":"Опиши промт, палитру, градиент, неоновый стиль или идею интерфейса.","home.suggest":"Подходящий инструмент","home.open":"Открыть инструмент","home.quick":"Быстрый старт","home.recent":"Недавние","home.creator":"Об авторе","home.creatorText":"18-летний frontend-разработчик и студент Колледжа цифровых технологий. Создаю современные интерактивные сайты и экспериментирую с дизайном, анимациями и frontend-технологиями.","home.more":"Подробнее обо мне",
    "library.title":"МОЯ БИБЛИОТЕКА","library.subtitle":"Все сохранённые эксперименты — их можно открыть, скопировать или изменить.","library.empty":"БИБЛИОТЕКА ПУСТА","library.emptyHint":"Создай первый эксперимент и сохрани его в системе.","library.favorites":"Избранное","library.search":"Поиск сохранённых систем...","library.renamed":"Проект переименован","library.deleted":"Проект удалён","library.duplicated":"Проект дублирован",
    "explore.title":"ИССЛЕДУЙ СИГНАЛ.","explore.subtitle":"Коллекция digital-экспериментов. Ищи, фильтруй, открывай и меняй.","explore.trending":"Популярное","explore.new":"Новое","explore.colors":"Цвета","explore.gradients":"Градиенты","explore.prompts":"Промты","explore.motion":"Анимация","explore.neon":"Неон","explore.noResults":"Ничего не найдено.",
    "about.label":"ОБ АВТОРЕ","about.hero":"АРСЕНИЙ ПЬЯНКОВ","about.roles":"18 ЛЕТ • FRONTEND-РАЗРАБОТЧИК • СТУДЕНТ • CREATIVE DEVELOPER","about.hello":"ПРИВЕТ, Я АРСЕНИЙ.","about.body1":"Мне 18 лет, я учусь в Колледже цифровых технологий по направлению frontend-разработки и занимаюсь созданием современных сайтов.","about.body2":"Мне особенно интересна та часть веб-разработки, где программирование пересекается с дизайном, анимацией и интерактивом. Я создаю сайты, которые запоминаются визуально и приятно ощущаются в использовании.","about.body3":"NEXUS LAB — один из моих проектов, где я объединяю программирование, дизайн, эксперименты и полезные digital-инструменты в одном интерфейсе.","about.what":"ЧТО Я ДЕЛАЮ","about.stack":"ТЕКУЩИЙ СТЕК","about.philosophy":"Я ХОЧУ СОЗДАВАТЬ НЕ ПРОСТО СТРАНИЦЫ, А ЦИФРОВЫЕ ВПЕЧАТЛЕНИЯ.","about.github":"Часть моих проектов и экспериментов с frontend-разработкой можно посмотреть на GitHub.","about.viewGithub":"Открыть GitHub",
    "contact.label":"ЕСТЬ ПРОЕКТ ИЛИ ИДЕЯ?","contact.hero":"ДАВАЙТЕ СОЗДАДИМ ЧТО-ТО НОВОЕ.","contact.role":"Frontend-разработчик • Студент Колледжа цифровых технологий","contact.email":"Почта","contact.telegram":"Telegram","contact.github":"GitHub","contact.discord":"Discord","contact.instagram":"Instagram","contact.vk":"VK","contact.copyDiscord":"Скопировать username","contact.discordCopied":"Discord скопирован","contact.final":"ДАВАЙТЕ СОЗДАДИМ ЧТО-ТО ДРУГОЕ.","contact.available":"Открыт к проектам и сотрудничеству","contact.send":"Написать на почту",
    "settings.title":"НАСТРОЙКИ NEXUS","settings.appearance":"Оформление","settings.language":"Язык","settings.motion":"Анимация","settings.dark":"Тёмная","settings.light":"Светлая","settings.system":"Системная","settings.full":"Полная","settings.reduced":"Уменьшенная","settings.off":"Выкл.","settings.english":"English","settings.russian":"Русский",
    "commands.title":"КОМАНДНАЯ ПАНЕЛЬ","commands.placeholder":"Поиск команд...","commands.empty":"Команда не найдена","commands.openTools":"Открыть Tool Hub","commands.openPrompt":"Открыть Prompt Lab","commands.openGradient":"Открыть Gradient Lab","commands.openColors":"Открыть Color Lab","commands.openNeon":"Открыть Neon Lab","commands.openMotion":"Открыть Motion Lab","commands.openLibrary":"Открыть библиотеку","commands.openGithub":"Открыть GitHub","commands.openTelegram":"Открыть Telegram","commands.copyDiscord":"Скопировать Discord","commands.sendEmail":"Написать на почту","commands.light":"Включить светлую тему","commands.dark":"Включить тёмную тему","commands.language":"Сменить язык",
    "onboarding.one":"ВЫБЕРИ ИНСТРУМЕНТ","onboarding.oneText":"Начни с быстрого старта, Tool Hub или командной панели.","onboarding.two":"СОЗДАЙ ЧТО-ТО","onboarding.twoText":"Каждая настройка сразу меняет живой preview.","onboarding.three":"СОХРАНИ ИЛИ ИЗМЕНИ","onboarding.threeText":"Результаты остаются в локальной библиотеке на этом устройстве.",
    "changelog.title":"ИЗМЕНЕНИЯ","changelog.subtitle":"История развития NEXUS LAB.","notFound.title":"СИГНАЛ ПОТЕРЯН","notFound.action":"Вернуться в Nexus"
  }
} as const;

export type MessageKey = keyof typeof messages.en;
export const translate = (language: Language, key: MessageKey) => messages[language][key] ?? messages.en[key];
