"use client";
import NexusShell from "./NexusShell";
import { useNexus } from "./NexusProvider";

const versions=[
  {version:"4.0.0",date:"20 AUG 2026",title:"RESPONSIVE RELIABILITY",items:["Replaced the decorative three-device Home mockup with one genuinely adaptive 1440 / 768 / 390 preview","Added container-query layout reflow, clear active tabs and mobile-safe spacing without desktop transform scaling","Corrected Code Lab presets to 1440 / 1366 / 768 / 390 plus Custom, live drag width feedback and reliable rotation","Rebuilt command search with bilingual fuzzy ranking and complete page / tool coverage","Stabilized Explore cards and modals, added real saving, and completed Library remix, sort and undo-delete workflows"]},
  {version:"3.2.0",date:"20 AUG 2026",title:"CINEMATIC INTERFACE",items:["Unified desktop navigation geometry with an aligned Tools item and compact morphing glass header","Interactive Tools mega-menu with grouped labs and contextual visual previews","Fullscreen mobile navigation with language, theme, settings and social controls","Cinematic Home hero with lightweight Digital Core 2.0, cursor inertia and scroll-driven transitions","Animated workflow, tool depth, Code to Result demo, responsive device switcher and live Chaos generation"]},
  {version:"3.1.0",date:"20 AUG 2026",title:"STABILITY & SCALE",items:["Expanded product homepage with workflow, demos, featured tools and workspace continuation","Rebuilt Code Lab core with isolated editor drafts, IndexedDB persistence and reliable autosave","Sandboxed preview with live and manual modes, console capture, responsive devices and quality checks","Project and file management, keyboard commands, import and verified real ZIP export","Faster route loading, mobile workspace navigation and performance-focused Monaco setup"]},
  {version:"3.0.0",date:"20 AUG 2026",title:"CREATIVE OPERATING SYSTEM",items:["Code Lab with Monaco editor, files, tabs and isolated live preview","Local projects, autosave, snapshots, notes, todos and data backup","Component library, snippets, design tokens and responsive quality checks","Real ZIP export, file import and direct Tool / Chaos Lab transfers","Lab Hub, rebuilt navigation and footer, mobile Code workflow and interaction fixes"]},
  {version:"2.0.0",date:"20 AUG 2026",title:"PRODUCT SYSTEM",items:["EN / RU localization","Dark, Light and System themes","Command palette and local project Library","Six expanded creative laboratories","Design DNA, Explore 2.0 and mobile workflow"]},
  {version:"1.1.0",date:"19 AUG 2026",title:"CREATIVE CORE",items:["Interactive Three.js digital core","Prompt, gradient, neon, glass, color and motion tools","Chaos Lab and curated Explore systems"]},
  {version:"1.0.0",date:"18 AUG 2026",title:"FIRST SIGNAL",items:["NEXUS LAB visual identity","Responsive neon interface","About and contact experiences"]}
];
export default function ChangelogClient(){const {t}=useNexus();return <NexusShell><main className="changelog-page"><section className="subpage-hero"><span>06 / SYSTEM LOG</span><h1>{t("changelog.title")}<br/><em>v4.0</em></h1><p>{t("changelog.subtitle")}</p></section><section className="version-list">{versions.map((version,index)=><article className="reveal" key={version.version}><div><span>{String(index+1).padStart(2,"0")}</span><strong>v{version.version}</strong><small>{version.date}</small></div><div><h2>{version.title}</h2><ul>{version.items.map(item=><li key={item}>{item}</li>)}</ul></div></article>)}</section></main></NexusShell>}
