"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import NexusShell from "./NexusShell";
import {useNexus} from "./NexusProvider";
import {ArrowUpRight,Braces,Code2,FlaskConical,MoveRight,Sparkles,WandSparkles,Zap} from "./NexusIcons";
import {CODE_INDEX_KEY} from "../lib/codeStorage";
import {ChaosDNA,createChaosSeed,generateChaosDNA} from "../lib/chaos";

type ToolKey="code"|"prompt"|"color"|"gradient"|"motion"|"chaos"|"neon"|"glass";
type RecentProject={id:string;name:string;updatedAt:number;type:string};

const tools:Array<{key:ToolKey;name:string;copy:[string,string];visual:string}>= [
  {key:"prompt",name:"PROMPT LAB",copy:["Turn a rough thought into a clear creative brief.","Превращает идею в точный креативный бриф."],visual:"prompt"},
  {key:"color",name:"COLOR LAB",copy:["Build accessible palettes with live contrast.","Собирает палитры и проверяет контраст."],visual:"color"},
  {key:"gradient",name:"GRADIENT LAB",copy:["Shape layered gradients and export clean CSS.","Создаёт многослойные градиенты и CSS."],visual:"gradient"},
  {key:"motion",name:"MOTION LAB",copy:["Tune timing, easing and interaction rhythm.","Настраивает ритм, easing и движение."],visual:"motion"},
  {key:"code",name:"CODE LAB",copy:["Code, preview, test and export a real frontend project.","Код, превью, тесты и реальный экспорт проекта."],visual:"code"},
  {key:"chaos",name:"CHAOS ENGINE",copy:["Generate a surprising direction when the canvas is blank.","Даёт неожиданное направление с чистого листа."],visual:"chaos"}
];
const workflow=["IDEA","STYLE","COLORS","MOTION","CODE","RESPONSIVE TEST","EXPORT"];
const reasons=[
  ["CONNECTED TOOLS","Move from idea to code without losing context."],["LIVE PREVIEW","See changes inside a sandboxed responsive canvas."],["RESPONSIVE FIRST","Test 1440, 768 and 390 pixels from one workspace."],["LOCAL FIRST","Projects remain on this device and work after load offline."],["SAVE + REMIX","Duplicate projects, preserve drafts and keep experimenting."],["REAL OUTPUT","Download source files and a verified ZIP, not a mock result."]
];
const demos=[
  {name:"SIGNAL / 01",type:"LANDING SYSTEM",style:"demo-signal"},{name:"AURORA / 02",type:"GRADIENT STUDY",style:"demo-aurora"},{name:"KINETIC / 03",type:"MOTION PROTOTYPE",style:"demo-kinetic"},{name:"OBJECT / 04",type:"INTERFACE COMPONENT",style:"demo-object"}
];
const responsiveModes={desktop:{label:"DESKTOP",width:1440,height:760},tablet:{label:"TABLET",width:768,height:840},mobile:{label:"MOBILE",width:390,height:760}} as const;

function detectTool(value:string):{key:ToolKey;name:string;reason:[string,string]}{
  const query=value.toLowerCase();
  if(/site|website|landing|portfolio|dashboard|app|component|html|css|javascript|сайт|лендинг|портфолио|дашборд|прилож|компонент|код/.test(query))return{key:"code",name:"CODE LAB",reason:["Best for building and testing a working interface.","Подходит для сборки и тестирования интерфейса."]};
  if(/color|palette|contrast|brand|цвет|палитр|контраст|бренд/.test(query))return{key:"color",name:"COLOR LAB",reason:["Best for palette and accessibility decisions.","Подходит для палитры и доступности."]};
  if(/gradient|mesh|aurora|градиент|аурор|фон/.test(query))return{key:"gradient",name:"GRADIENT LAB",reason:["Best for layered backgrounds and CSS export.","Подходит для фонов и экспорта CSS."]};
  if(/motion|animate|animation|transition|easing|анимац|движ|переход/.test(query))return{key:"motion",name:"MOTION LAB",reason:["Best for timing and interaction rhythm.","Подходит для тайминга и ритма интерфейса."]};
  if(/neon|glow|light|неон|свечение|свет/.test(query))return{key:"neon",name:"NEON LAB",reason:["Best for controlled glow and luminous type.","Подходит для свечения и неоновой типографики."]};
  if(/glass|blur|стекл|блюр/.test(query))return{key:"glass",name:"GLASS LAB",reason:["Best for glass surfaces and depth.","Подходит для стеклянных поверхностей и глубины."]};
  if(/random|surprise|stuck|idea|хаос|случайн|не знаю|идея/.test(query))return{key:"chaos",name:"CHAOS ENGINE",reason:["Best for finding an unexpected starting direction.","Подходит для поиска неожиданной точки старта."]};
  return{key:"prompt",name:"PROMPT LAB",reason:["Best for turning a rough thought into a useful brief.","Подходит для превращения мысли в точный бриф."]};
}
const toolHref=(key:ToolKey,idea="")=>key==="code"?"/code":key==="chaos"?"/lab/chaos":`/tools?tool=${key}${idea?`&idea=${encodeURIComponent(idea)}`:""}`;

export default function HomeClient(){
  const {language,openCommands,motion,toast}=useNexus();
  const word=(en:string,ru:string)=>language==="ru"?ru:en;
  const rootRef=useRef<HTMLElement>(null);
  const codeDemoRef=useRef<HTMLDivElement>(null);
  const [idea,setIdea]=useState("");
  const [online,setOnline]=useState(true);
  const [recentProject,setRecentProject]=useState<RecentProject|null>(null);
  const [codeStage,setCodeStage]=useState(0);
  const [demoVisible,setDemoVisible]=useState(false);
  const [deviceMode,setDeviceMode]=useState<"desktop"|"tablet"|"mobile">("desktop");
  const [chaosDna,setChaosDna]=useState<ChaosDNA>(()=>generateChaosDNA("NX-482914"));
  const suggestion=useMemo(()=>detectTool(idea),[idea]);

  useEffect(()=>{const timer=setTimeout(()=>{setOnline(navigator.onLine);try{setIdea(localStorage.getItem("nexus-home-draft")||"");const index=JSON.parse(localStorage.getItem(CODE_INDEX_KEY)||"null") as {activeProjectId?:string;projects?:RecentProject[]}|null;const active=index?.projects?.find(project=>project.id===index.activeProjectId)||index?.projects?.[0]||null;setRecentProject(active)}catch{setRecentProject(null)}},0);const sync=()=>setOnline(navigator.onLine);addEventListener("online",sync);addEventListener("offline",sync);return()=>{clearTimeout(timer);removeEventListener("online",sync);removeEventListener("offline",sync)}},[]);
  useEffect(()=>{const node=codeDemoRef.current;if(!node)return;const observer=new IntersectionObserver(entries=>setDemoVisible(Boolean(entries[0]?.isIntersecting)),{rootMargin:"120px"});observer.observe(node);return()=>observer.disconnect()},[]);
  useEffect(()=>{if(!demoVisible||motion==="off")return;const timer=window.setInterval(()=>setCodeStage(stage=>(stage+1)%3),1700);return()=>clearInterval(timer)},[demoVisible,motion]);
  useEffect(()=>{const root=rootRef.current;if(!root)return;let disposed=false;let animationContext:{revert:()=>void}|null=null;let pointerFrame=0;let targetX=0,targetY=0,currentX=0,currentY=0;const full=motion==="full"&&matchMedia("(pointer:fine)").matches&&!matchMedia("(prefers-reduced-motion: reduce)").matches&&innerWidth>760;const pointer=(event:PointerEvent)=>{const box=root.getBoundingClientRect();targetX=(event.clientX-box.left)/Math.max(1,box.width)-.5;targetY=event.clientY/Math.max(1,innerHeight)-.5};const follow=()=>{currentX+=(targetX-currentX)*.065;currentY+=(targetY-currentY)*.065;root.style.setProperty("--hero-x",currentX.toFixed(4));root.style.setProperty("--hero-y",currentY.toFixed(4));pointerFrame=requestAnimationFrame(follow)};if(full){root.addEventListener("pointermove",pointer,{passive:true});pointerFrame=requestAnimationFrame(follow)}void(async()=>{const [{gsap},{ScrollTrigger}]=await Promise.all([import("gsap"),import("gsap/ScrollTrigger")]);if(disposed)return;gsap.registerPlugin(ScrollTrigger);animationContext=gsap.context(()=>{if(motion==="off")return;gsap.from(".hero-line-inner",{yPercent:115,rotateX:-18,filter:"blur(10px)",duration:1.05,stagger:.12,ease:"power4.out",delay:.08});gsap.from(".home4-copy>p,.home4-actions,.home4-command",{y:24,opacity:0,duration:.75,stagger:.08,ease:"power3.out",delay:.38});if(!full)return;gsap.to(".nexus-core-2",{scale:2.45,opacity:.16,ease:"none",scrollTrigger:{trigger:".home4-hero",start:"top top",end:"bottom top",scrub:1}});gsap.to(".hero-portal",{scale:8,opacity:.95,ease:"none",scrollTrigger:{trigger:".home4-hero",start:"45% top",end:"bottom top",scrub:1}});gsap.to(".hero-grid",{yPercent:24,ease:"none",scrollTrigger:{trigger:".home4-hero",start:"top top",end:"bottom top",scrub:1.2}});gsap.to(".home4-scroll-cue",{opacity:0,y:20,scrollTrigger:{trigger:".home4-hero",start:"top top",end:"18% top",scrub:true}});gsap.to(".reading-line span",{color:"var(--white)",stagger:.035,ease:"none",scrollTrigger:{trigger:".reading-line",start:"top 82%",end:"bottom 42%",scrub:true}});gsap.fromTo(".workflow-energy b",{scaleX:0},{scaleX:1,ease:"none",scrollTrigger:{trigger:".home4-flow",start:"top 75%",end:"bottom 48%",scrub:true}});gsap.from(".home4-tool",{y:80,opacity:0,rotateX:8,stagger:.08,ease:"power3.out",scrollTrigger:{trigger:".home4-tool-grid",start:"top 78%",end:"top 36%",scrub:1}});gsap.from(".responsive-demo",{y:90,opacity:0,ease:"power3.out",scrollTrigger:{trigger:".responsive-stage",start:"top 78%",end:"top 40%",scrub:1}});gsap.from(".home4-type-transition span",{xPercent:(index:number)=>index%2?35:-35,opacity:.05,stagger:.08,ease:"none",scrollTrigger:{trigger:".home4-type-transition",start:"top 90%",end:"bottom 25%",scrub:1}})},root);ScrollTrigger.refresh()})();return()=>{disposed=true;animationContext?.revert();cancelAnimationFrame(pointerFrame);root.removeEventListener("pointermove",pointer);root.style.removeProperty("--hero-x");root.style.removeProperty("--hero-y")}},[motion]);
  const updateIdea=(value:string)=>{setIdea(value);localStorage.setItem("nexus-home-draft",value)};
  const openSuggestion=()=>{location.href=toolHref(suggestion.key,idea)};
  const tiltCard=(event:React.PointerEvent<HTMLAnchorElement>)=>{if(motion!=="full"||event.pointerType==="touch")return;const card=event.currentTarget;const box=card.getBoundingClientRect();const x=(event.clientX-box.left)/box.width;const y=(event.clientY-box.top)/box.height;card.style.setProperty("--card-x",`${x*100}%`);card.style.setProperty("--card-y",`${y*100}%`);card.style.setProperty("--tilt-x",`${(x-.5)*7}deg`);card.style.setProperty("--tilt-y",`${(.5-y)*7}deg`)};
  const resetCard=(event:React.PointerEvent<HTMLAnchorElement>)=>{event.currentTarget.style.removeProperty("--tilt-x");event.currentTarget.style.removeProperty("--tilt-y")};
  const generateHomeChaos=()=>{const next=generateChaosDNA(createChaosSeed());setChaosDna(next);localStorage.setItem("nexus-chaos-draft",JSON.stringify(next));toast("CHAOS SIGNAL GENERATED","info")};

  return <NexusShell><main ref={rootRef} className="home-page home-v4 home-cinematic">
    <section className="home4-hero">
      <div className="hero-grid"/><div className="hero-particles">{Array.from({length:18},(_,index)=><i key={index} style={{"--particle":index} as React.CSSProperties}/>)}</div><div className="hero-fragments"><i>SYS/01</i><i>CORE ONLINE</i><i>BUILD 4.0</i></div>
      <div className="nexus-core-2" aria-label="Interactive digital core"><div className="core-glow"/><div className="core-ring ring-a"/><div className="core-ring ring-b"/><div className="core-ring ring-c"/><div className="core-glass"><i/><b>N</b></div><div className="core-orbit"><i/><i/><i/></div><div className="hero-portal"/></div>
      <div className="home4-kicker"><span>NEXUS LAB // CREATIVE DEVELOPMENT SYSTEM</span><button onClick={openCommands}>CTRL + K / QUICK SEARCH</button></div>
      <div className="home4-copy"><p className="micro">INTERACTIVE DIGITAL LAB / 2026</p><h1><span className="hero-line depth-back"><b className="hero-line-inner">THINK. DESIGN.</b></span><em className="hero-line depth-front"><b className="hero-line-inner">CODE. BUILD.</b></em></h1><p>{word("An interactive digital lab for turning ideas into style, motion and working frontend code — inside one connected local-first workspace.","Интерактивная цифровая лаборатория, где идея превращается в стиль, движение и рабочий frontend-код — в одном связанном local-first пространстве.")}</p><div className="home4-actions"><a className="primary-btn" href="#featured" data-cursor="ENTER">ENTER THE LAB <ArrowUpRight/></a><a href="/code" data-cursor="OPEN">OPEN CODE LAB <Code2/></a><a href="/tools" data-cursor="VIEW">EXPLORE TOOLS <FlaskConical/></a></div></div>
      <div className="home4-command"><span>WHAT DO YOU WANT TO CREATE?</span><div><b>›</b><input value={idea} onChange={event=>updateIdea(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")openSuggestion()}} placeholder={word("A responsive portfolio with kinetic typography…","Адаптивное портфолио с кинетической типографикой…")}/><button onClick={openSuggestion}>OPEN <ArrowUpRight/></button></div><footer><span>{word("RECOMMENDED","РЕКОМЕНДАЦИЯ")}: <strong>{suggestion.name}</strong></span><p>{word(...suggestion.reason)}</p></footer></div>
      <aside className="home4-status"><span><i className={online?"":"offline"}/>{online?"SYSTEM ONLINE":"OFFLINE / LOCAL MODE"}</span><span><b>8+</b> CREATIVE TOOLS</span><span><b>READY</b> WORKSPACE</span><span><b>LOCAL</b> FIRST</span></aside>
      <div className="home4-scroll-cue"><span>SCROLL TO ENTER</span><i/></div>
    </section>

    <section className="home4-intro">
      <div><p className="micro">01 / WHAT IS NEXUS LAB</p><h2>{word("A connected system for digital creation.","Связанная система для цифрового творчества.")}</h2></div>
      <div><p className="reading-line">{word("NEXUS LAB IS A CREATIVE ENVIRONMENT WHERE DESIGN, MOTION AND CODE WORK TOGETHER.","NEXUS LAB — ТВОРЧЕСКАЯ СРЕДА, ГДЕ ДИЗАЙН, ДВИЖЕНИЕ И КОД РАБОТАЮТ ВМЕСТЕ.").split(" ").map((item,index)=><span className={/DESIGN|MOTION|CODE|ДИЗАЙН|ДВИЖЕНИЕ|КОД/.test(item)?"accent":""} key={`${item}-${index}`}>{item} </span>)}</p><p>{word("Each focused tool advances one part of the process. Code Lab connects the result into a real project you can test and export.","Каждый инструмент продвигает свою часть процесса, а Code Lab соединяет результат в реальный проект, который можно проверить и экспортировать.")}</p></div>
    </section>
    <section className="home4-flow"><header><span>ONE IDEA.</span><strong>ONE WORKFLOW.</strong></header><i className="workflow-energy"><b/></i><div>{workflow.map((step,index)=><span key={step}><b>{String(index+1).padStart(2,"0")}</b>{step}{index<workflow.length-1&&<MoveRight/>}</span>)}</div></section>
    <section className="home4-marquee" aria-label="Design Code Motion Create Experiment Ship"><div>DESIGN — CODE — MOTION — CREATE — EXPERIMENT — SHIP — DESIGN — CODE — MOTION — CREATE —</div></section>

    <section id="featured" className="home4-featured"><div className="home4-section-head"><span>02 / FEATURED TOOLS</span><h2>{word("Choose the right instrument.","Выбери нужный инструмент.")}</h2><p>{word("Focused modules. Shared creative direction.","Точные модули. Единое творческое направление.")}</p></div><div className="home4-tool-grid">{tools.map((tool,index)=><a href={toolHref(tool.key)} className={`home4-tool tool-${tool.visual}`} key={tool.key} data-cursor="OPEN" onPointerMove={tiltCard} onPointerLeave={resetCard}><header><span>0{index+1}</span><ArrowUpRight/></header><div className="tool-mini"><i/><i/><i/><b/></div><h3>{tool.name}</h3><p>{word(...tool.copy)}</p><span className="tool-card-cta">ENTER LAB <ArrowUpRight/></span></a>)}</div></section>

    <section className="home4-code-promo"><div><p className="micro">03 / CORE WORKSPACE</p><h2>CODE. PREVIEW.<br/><em>TEST. SHIP.</em></h2><p>{word("A fast HTML, CSS and JavaScript workspace with isolated file models, sandboxed preview, real console, responsive testing, local autosave and ZIP export.","Быстрая среда для HTML, CSS и JavaScript с отдельными моделями файлов, безопасным превью, консолью, адаптивным тестом, локальным автосохранением и ZIP-экспортом.")}</p><ul><li>MONACO EDITOR</li><li>LIVE + MANUAL PREVIEW</li><li>PROJECTS + FILES</li><li>RESPONSIVE DEVICES</li></ul><a className="primary-btn" href="/code" data-cursor="TRY">OPEN CODE LAB <ArrowUpRight/></a></div><div ref={codeDemoRef} className={`code-promo-window code-stage-${codeStage}`}><header><b>NEXUS° CODE LAB</b><span>● LIVE / AUTO DEMO</span></header><aside><span>▾ PROJECT</span><b>index.html</b><b className="active">styles.css</b><b>script.js</b></aside><pre><span><i>01</i> <em>.hero {'{'}</em></span>{"\n"}<span className="code-line-radius"><i>02</i>   border-radius: <b>24px</b>;</span>{"\n"}<span className="code-line-background"><i>03</i>   background: <b>linear-gradient(135deg,#65eaff,#8a5cff)</b>;</span>{"\n"}<span><i>04</i>   transition: <b>.6s ease</b>;</span>{"\n"}<span><i>05</i> <em>{'}'}</em></span><span className="typing-caret">▋</span></pre><section><div className="code-demo-result"><span>NEXUS / ONLINE</span><strong>CODE<br/>→ RESULT.</strong><p>LIVE RESPONSIVE SURFACE</p><button onClick={()=>location.href="/code"}>INITIALIZE ↗</button></div></section><footer><span>CSS</span><span>Ln {codeStage+2}, Col 18</span><span>390px</span><b>0 PROBLEMS</b></footer></div></section>

    <section className={`home4-responsive device-mode-${deviceMode}`}>
      <div className="home4-section-head"><span>04 / RESPONSIVE FIRST</span><h2>BUILD FOR<br/><em>EVERY SCREEN.</em></h2><p>{word("One project. Three essential viewports. Resize further inside Code Lab.","Один проект. Три главных экрана. Ещё больше размеров внутри Code Lab.")}</p></div>
      <div className="device-switcher" role="tablist" aria-label="Device preview">{(Object.keys(responsiveModes) as Array<keyof typeof responsiveModes>).map(mode=><button role="tab" aria-selected={deviceMode===mode} className={deviceMode===mode?"active":""} onClick={()=>setDeviceMode(mode)} key={mode}><b>{responsiveModes[mode].label}</b><span>/ {responsiveModes[mode].width}</span><i aria-hidden="true">●</i></button>)}</div>
      <div className="responsive-stage"><article className={`responsive-demo viewport-${deviceMode}`} style={{"--preview-width":`${responsiveModes[deviceMode].width}px`,"--preview-height":`${responsiveModes[deviceMode].height}px`} as React.CSSProperties} aria-live="polite">
        <header><div><i/><i/><i/></div><strong>{responsiveModes[deviceMode].label} / {responsiveModes[deviceMode].width}px</strong><span>● LIVE LAYOUT</span></header>
        <div className="responsive-app"><nav><strong className="responsive-logo">NEXUS°</strong><div><span>WORK</span><span>TOOLS</span><span>ABOUT</span></div><span className="responsive-menu">MENU <b>☰</b></span></nav><main><section className="responsive-copy"><span>RESPONSIVE SYSTEM / 2026</span><h3>ONE IDEA.<br/><em>ANY SCREEN.</em></h3><p>{word("The same content hierarchy reorganizes itself at every breakpoint.","Одна и та же иерархия контента перестраивается на каждом breakpoint.")}</p><span className="responsive-cta">EXPLORE SYSTEM ↗</span></section><aside><i/><strong>LIVE<br/>SIGNAL</strong><span>{responsiveModes[deviceMode].width} PX</span></aside></main><section className="responsive-cards"><article><span>01 / DESIGN</span><b>VISUAL SYSTEM</b><i/></article><article><span>02 / MOTION</span><b>KINETIC FLOW</b><i/></article><article><span>03 / CODE</span><b>REAL OUTPUT</b><i/></article></section></div>
        <footer><span>CONTAINER QUERIES / ACTIVE</span><b>{responsiveModes[deviceMode].width} × {responsiveModes[deviceMode].height}</b></footer>
      </article></div>
    </section>

    <section className="home4-design"><div><p className="micro">05 / DESIGN SYSTEM</p><h2>BUILD<br/>YOUR STYLE.</h2><p>{word("Define the visual language once, then carry it across tools and projects.","Определи визуальный язык один раз и перенеси его в инструменты и проекты.")}</p><a href="/tools?tool=color">OPEN COLOR LAB <ArrowUpRight/></a></div><div className="design-specimen"><section><span>COLORS</span><div className="swatches"><i/><i/><i/><i/><i/></div></section><section><span>TYPOGRAPHY</span><b>Aa</b><strong>INTER / 800</strong></section><section><span>RADIUS</span><i className="radius-demo"/></section><section><span>GLASS + GLOW</span><i className="glass-demo"/></section><section><span>MOTION</span><i className="motion-demo"/></section></div></section>

    <section className="home4-chaos" style={{"--chaos-a":chaosDna.palette[0],"--chaos-b":chaosDna.palette[1],"--chaos-c":chaosDna.palette[2]} as React.CSSProperties}><div className="chaos-field"><i/><i/><i/><b>?</b><div className="home-chaos-result"><span>SEED / {chaosDna.seed}</span><strong>{chaosDna.name}</strong><p>{chaosDna.ui} · {chaosDna.motion}</p><div>{chaosDna.palette.map(color=><i key={color} style={{background:color}}/>)}</div></div></div><div><p className="micro">06 / CREATIVE RANDOMIZER</p><h2>DON&apos;T KNOW<br/>WHERE TO START?</h2><strong>GENERATE CHAOS.</strong><p>{word("Let the system combine format, style, color and motion into an unexpected direction — then send it into your workflow.","Пусть система соединит формат, стиль, цвет и движение в неожиданное направление — а затем отправит его в твой workflow.")}</p><div className="chaos-actions"><button className="primary-btn" onClick={generateHomeChaos} data-cursor="GENERATE"><Zap/> GENERATE CHAOS</button><a href="/lab/chaos">OPEN IN LAB <ArrowUpRight/></a></div></div></section>

    <section className="home4-how"><div className="home4-section-head"><span>07 / HOW IT WORKS</span><h2>{word("From blank canvas to real output.","От чистого листа до реального результата.")}</h2></div><ol>{[["CHOOSE","Pick a focused tool or start with your idea."],["CREATE","Shape colors, prompts, motion or code."],["TEST","Use live preview and responsive devices."],["SAVE","Keep projects locally and return later."],["EXPORT","Take clean files and continue anywhere."]].map((item,index)=><li key={item[0]}><span>0{index+1}</span><h3>{item[0]}</h3><p>{item[1]}</p></li>)}</ol></section>

    <section className="home4-workspace"><div><p className="micro">08 / YOUR WORKSPACE</p><h2>{word("Your ideas stay within reach.","Твои идеи всегда под рукой.")}</h2><p>{word("Projects, saved outputs, favorites and recent experiments live in a local-first library on this device.","Проекты, сохранённые результаты, избранное и недавние эксперименты находятся в local-first библиотеке на этом устройстве.")}</p><div className="workspace-links"><a href="/code"><Code2/> PROJECTS <ArrowUpRight/></a><a href="/library"><Braces/> LIBRARY <ArrowUpRight/></a><a href="/explore"><Sparkles/> EXPERIMENTS <ArrowUpRight/></a></div></div>{recentProject?<aside><span>CONTINUE WHERE YOU LEFT OFF</span><h3>{recentProject.name}</h3><p>{recentProject.type} · {new Date(recentProject.updatedAt).toLocaleString()}</p><a href="/code">OPEN WORKSPACE <ArrowUpRight/></a></aside>:<aside className="workspace-empty"><span>WORKSPACE READY</span><h3>{word("No local projects yet.","Локальных проектов пока нет.")}</h3><p>{word("Create the first project — it will appear here automatically.","Создай первый проект — он автоматически появится здесь.")}</p><a href="/code">CREATE PROJECT <ArrowUpRight/></a></aside>}</section>

    <section className="home4-demos"><div className="home4-section-head"><span>09 / FROM THE LAB</span><h2>{word("Digital experiments in motion.","Цифровые эксперименты в движении.")}</h2><a href="/explore">EXPLORE ALL <ArrowUpRight/></a></div><div>{demos.map((demo,index)=><a href="/explore" key={demo.name}><div className={demo.style}><i/><i/><b>{index+1}</b></div><span>{demo.type}</span><h3>{demo.name}</h3></a>)}</div></section>

    <section className="home4-why"><div className="home4-section-head"><span>10 / WHY NEXUS</span><h2>{word("Less friction. More signal.","Меньше трения. Больше сигнала.")}</h2></div><div>{reasons.map((reason,index)=><article key={reason[0]}><span>0{index+1}</span><h3>{reason[0]}</h3><p>{reason[1]}</p></article>)}</div></section>

    <section className="home4-type-transition" aria-hidden="true"><span>CREATE.</span><span>TEST.</span><span>REMIX.</span></section>
    <section className="home4-stack"><span>BUILT WITH</span>{["REACT","TYPESCRIPT","VITE","GSAP","THREE.JS","WEBGL"].map(item=><b key={item}>{item}</b>)}</section>
    <section className="home4-author"><div className="author-mark"><i/><b>AP</b></div><div><p className="micro">11 / CREATED BY</p><h2>ARSENII<br/><em>PIANKOV.</em></h2><p>{word("18 years old. Student at the College of Digital Technologies. Frontend developer exploring the space between interface design, motion and code.","18 лет. Студент Колледжа цифровых технологий. Frontend-разработчик, исследующий пространство между дизайном интерфейсов, движением и кодом.")}</p><a href="/about">ABOUT THE CREATOR <ArrowUpRight/></a></div></section>
    <section className="home4-contact"><div className="final-energy-line"/><WandSparkles/><p>HAVE AN IDEA?</p><h2>LET&apos;S BUILD<br/>SOMETHING<br/><em>DIFFERENT.</em></h2><a className="primary-btn" data-cursor="CONNECT" href="mailto:pyankovad2606@gmail.com">LET&apos;S CONNECT <ArrowUpRight/></a><small>pyankovad2606@gmail.com</small><div><a href="https://t.me/PlugOnPercs" target="_blank" rel="noopener noreferrer">TELEGRAM @PlugOnPercs</a><a href="https://github.com/Diamondz52" target="_blank" rel="noopener noreferrer">GITHUB / Diamondz52</a></div></section>
  </main></NexusShell>;
}
