"use client";
import {useEffect,useMemo,useState} from "react";
import NexusShell from "./NexusShell";
import {deleteLibraryItem,duplicateLibraryItem,getLibrary,LibraryItem,restoreLibraryItem,updateLibraryItem} from "../lib/library";
import {useNexus} from "./NexusProvider";

const filters=["all","favorites","prompt","palette","gradient","neon","glass","motion","chaos"];
type SortMode="newest"|"oldest"|"name";
const toolRoute=(item:LibraryItem)=>item.type==="chaos"?`/lab/chaos?library=${item.id}`:`/tools?tool=${item.type==="palette"?"color":item.type}&library=${item.id}`;
const normalize=(value:string)=>value.toLowerCase().replaceAll("ё","е").trim();

export default function LibraryClient(){
  const {language,t,copy,toast}=useNexus();
  const [items,setItems]=useState<LibraryItem[]>([]);const [filter,setFilter]=useState("all");const [search,setSearch]=useState("");const [sort,setSort]=useState<SortMode>("newest");const [deleted,setDeleted]=useState<LibraryItem|null>(null);
  const refresh=()=>setItems(getLibrary());
  useEffect(()=>{const timer=setTimeout(refresh,0);window.addEventListener("nexus-library",refresh);return()=>{clearTimeout(timer);window.removeEventListener("nexus-library",refresh)}},[]);
  useEffect(()=>{if(!deleted)return;const timer=setTimeout(()=>setDeleted(null),6000);return()=>clearTimeout(timer)},[deleted]);
  const shown=useMemo(()=>{const query=normalize(search);return items.filter(item=>(filter==="all"||(filter==="favorites"?item.favorite:item.type===filter))&&(!query||normalize(`${item.name} ${item.type}`).includes(query))).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="oldest"?Date.parse(a.updatedAt)-Date.parse(b.updatedAt):Date.parse(b.updatedAt)-Date.parse(a.updatedAt))},[filter,items,search,sort]);
  const rename=(item:LibraryItem)=>{const name=prompt(t("common.rename"),item.name)?.trim();if(name){updateLibraryItem(item.id,{name});toast(t("library.renamed"))}};
  const remove=(item:LibraryItem)=>{setDeleted(item);deleteLibraryItem(item.id);toast(t("library.deleted"))};
  const undo=()=>{if(!deleted)return;restoreLibraryItem(deleted);setDeleted(null);toast(language==="ru"?"Проект восстановлен":"Project restored")};
  return <NexusShell><main className="library-page"><section className="subpage-hero library-hero"><span>04 / LOCAL STORAGE</span><h1>{t("library.title")}</h1><p>{t("library.subtitle")}</p></section><section className="library-toolbar"><label><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={t("library.search")}/></label><div>{filters.map(item=><button className={filter===item?"active":""} key={item} onClick={()=>setFilter(item)}>{item==="all"?t("common.all"):item==="favorites"?`♥ ${t("library.favorites")}`:item.toUpperCase()}</button>)}</div><select aria-label="Sort saved projects" value={sort} onChange={event=>setSort(event.target.value as SortMode)}><option value="newest">{language==="ru"?"СНАЧАЛА НОВЫЕ":"NEWEST FIRST"}</option><option value="oldest">{language==="ru"?"СНАЧАЛА СТАРЫЕ":"OLDEST FIRST"}</option><option value="name">A → Z</option></select></section>{shown.length?<section className="library-grid">{shown.map((item,index)=><article key={item.id} className={`library-card type-${item.type}`}><div className="library-visual"><span>{String(index+1).padStart(2,"0")} / {item.type.toUpperCase()}</span><div className="library-orb"><i/><i/></div><button aria-label="Favorite" className={item.favorite?"active":""} onClick={()=>updateLibraryItem(item.id,{favorite:!item.favorite})}>{item.favorite?"♥":"♡"}</button></div><div className="library-info"><small>{new Date(item.updatedAt).toLocaleDateString(language==="ru"?"ru-RU":"en-US")}</small><h2>{item.name}</h2><div><a href={toolRoute(item)}>{t("common.open").toUpperCase()}</a><a href={`${toolRoute(item)}&mode=remix`}>{t("common.remix").toUpperCase()}</a><button onClick={()=>copy(JSON.stringify(item.data,null,2))}>{t("common.copy").toUpperCase()}</button><button onClick={()=>rename(item)}>{t("common.rename").toUpperCase()}</button><button onClick={()=>{duplicateLibraryItem(item.id);toast(t("library.duplicated"))}}>{t("common.duplicate").toUpperCase()}</button><button onClick={()=>remove(item)}>{t("common.delete").toUpperCase()}</button></div></div></article>)}</section>:<section className="library-empty"><div className="empty-core"><i/><i/><b/></div><h2>{t("library.empty")}</h2><p>{t("library.emptyHint")}</p><a href="/tools" className="primary-btn">OPEN LAB ↗</a></section>}{deleted&&<div className="library-undo" role="status"><span>{deleted.name} · {language==="ru"?"удалён":"deleted"}</span><button onClick={undo}>UNDO</button><button aria-label={t("common.close")} onClick={()=>setDeleted(null)}>×</button></div>}</main></NexusShell>;
}
