"use client";
import { useEffect,useMemo,useState } from "react";
import NexusShell from "./NexusShell";
import { useNexus } from "./NexusProvider";
import { getLibrary,LibraryType,saveLibraryItem } from "../lib/library";

const labs=["PROMPT","GRADIENT","NEON","GLASS","COLOR","MOTION"] as const;type Lab=typeof labs[number];
const hslHex=(h:number,s:number,l:number)=>{s/=100;l/=100;const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs(h/60%2-1)),m=l-c/2;let r=0,g=0,b=0;if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x}return"#"+[r,g,b].map(v=>Math.round((v+m)*255).toString(16).padStart(2,"0")).join("").toUpperCase()};
const luminance=(color:string)=>{const c=color.replace("#","");const values=[0,2,4].map(i=>parseInt(c.slice(i,i+2),16)/255).map(x=>x<=.03928?x/12.92:Math.pow((x+.055)/1.055,2.4));return .2126*values[0]+.7152*values[1]+.0722*values[2]};const contrast=(a:string,b:string)=>{const [x,y]=[luminance(a),luminance(b)].sort((m,n)=>n-m);return (x+.05)/(y+.05)};
function Range({label,value,min,max,onChange,suffix=""}:{label:string,value:number,min:number,max:number,onChange:(n:number)=>void,suffix?:string}){return <label className="control range-control"><span>{label}<b>{value}{suffix}</b></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(+e.target.value)}/></label>}
function Segments({values,value,onChange}:{values:string[];value:string;onChange:(v:string)=>void}){return <div className="segments">{values.map(x=><button className={value===x?"active":""} key={x} onClick={()=>onChange(x)}>{x}</button>)}</div>}

export default function ToolsClient(){const {t,copy,toast}=useNexus();const [active,setActive]=useState<Lab>("PROMPT");const [fullscreen,setFullscreen]=useState(false);const [,setOutputTab]=useState<"code"|"preview">("preview");
  const [idea,setIdea]=useState("neon car in tokyo"),[category,setCategory]=useState("IMAGE"),[promptMode,setPromptMode]=useState("DETAILED"),[preset,setPreset]=useState("CINEMATIC"),[style,setStyle]=useState("futuristic"),[mood,setMood]=useState("cinematic"),[lighting,setLighting]=useState("cyan and violet practical light"),[camera,setCamera]=useState("wide angle"),[ratio,setRatio]=useState("16:9"),[prompt,setPrompt]=useState("neon car in tokyo, cinematic image, futuristic style, cinematic mood, cyan and violet practical light, wide angle composition, aspect ratio 16:9.");
  const [g1,setG1]=useState("#64efff"),[g2,setG2]=useState("#8b5cff"),[g3,setG3]=useState("#ff4fbd"),[angle,setAngle]=useState(135),[gradientType,setGradientType]=useState("LINEAR"),[intensity,setIntensity]=useState(100),[noise,setNoise]=useState(8),[speed,setSpeed]=useState(6);const [gHistory,setGHistory]=useState<Array<[string,string,string,number,string]>>([]),[gFuture,setGFuture]=useState<Array<[string,string,string,number,string]>>([]);
  const [neonText,setNeonText]=useState("NEXUS"),[neonColor,setNeonColor]=useState("#64efff"),[outerColor,setOuterColor]=useState("#8b5cff"),[glow,setGlow]=useState(42),[blur,setBlur]=useState(8),[spread,setSpread]=useState(2),[neonSize,setNeonSize]=useState(90),[letter,setLetter]=useState(3),[flicker,setFlicker]=useState(true),[pulse,setPulse]=useState(false);
  const [opacity,setOpacity]=useState(8),[glassBlur,setGlassBlur]=useState(24),[saturation,setSaturation]=useState(120),[border,setBorder]=useState(18),[borderWidth,setBorderWidth]=useState(1),[radius,setRadius]=useState(28),[glassGlow,setGlassGlow]=useState(22),[glassNoise,setGlassNoise]=useState(5);
  const [scheme,setScheme]=useState("NEON"),[palette,setPalette]=useState(["#0A0B10","#2731B8","#755BFF","#65E8FF","#F4F7FF"]),[locks,setLocks]=useState([false,false,false,false,false]);
  const [motion,setMotion]=useState("reveal"),[motionCategory,setMotionCategory]=useState("ENTRANCE"),[duration,setDuration]=useState(800),[delay,setDelay]=useState(0),[easing,setEasing]=useState("EASE OUT"),[iterations,setIterations]=useState(1),[playing,setPlaying]=useState(true),[motionKey,setMotionKey]=useState(0);
  const gradient=useMemo(()=>gradientType==="RADIAL"?`radial-gradient(circle at 60% 40%,${g1},${g2},${g3})`:gradientType==="CONIC"?`conic-gradient(from ${angle}deg,${g1},${g2},${g3},${g1})`:gradientType==="MESH"?`radial-gradient(at 20% 20%,${g1},transparent 50%),radial-gradient(at 80% 30%,${g2},transparent 55%),radial-gradient(at 50% 90%,${g3},#06070c 70%)`:gradientType==="AURORA"?`linear-gradient(${angle}deg,${g1},${g2} 42%,${g3} 72%,${g1})`:`linear-gradient(${angle}deg,${g1},${g2},${g3})`,[angle,g1,g2,g3,gradientType]);
  const gradientCss=`background: ${gradient};\nfilter: saturate(${intensity}%);\nanimation: nexus-aurora ${speed}s ease-in-out infinite;`;
  const neonCss=`color:${neonColor};font-size:${neonSize}px;letter-spacing:${letter}px;text-shadow:0 0 ${spread}px #fff,0 0 ${blur}px ${neonColor},0 0 ${glow}px ${neonColor},0 0 ${glow*2}px ${outerColor};${flicker?"animation:nexus-flicker 3.5s infinite;":""}${pulse?"animation:nexus-pulse 2s ease-in-out infinite;":""}`;
  const glassCss=`background:rgba(255,255,255,${opacity/100});backdrop-filter:blur(${glassBlur}px) saturate(${saturation}%);border:${borderWidth}px solid rgba(255,255,255,${border/100});border-radius:${radius}px;box-shadow:0 0 ${glassGlow}px rgba(101,234,255,.16);`;
  const motionCss=`animation:nexus-${motion} ${duration}ms ${easing.toLowerCase().replaceAll(" ","-")} ${delay}ms ${iterations===9?"infinite":iterations};`;
  const promptOutput=()=>{const core=`${idea.trim()}, ${preset.toLowerCase()} ${category.toLowerCase()}, ${style} style, ${mood} mood, ${lighting}, ${camera} composition, aspect ratio ${ratio}`;const detail=`Environment with layered depth and clear visual hierarchy. Materials are tactile and precisely rendered. Controlled highlights, realistic reflections, purposeful negative space.`;const ultra=`Camera behavior: ${camera}, balanced framing and cinematic depth of field. Color direction: refined cyan, violet and contextual accents. Production quality: polished art direction, coherent materials, sharp focal detail, subtle atmosphere. Constraints: no watermark, no random text, no clutter.`;setPrompt(promptMode==="SIMPLE"?core:promptMode==="DETAILED"?`${core}. ${detail}`:`${core}. ${detail} ${ultra}`)};
  const remixPrompt=()=>{const presets=["CINEMATIC","EDITORIAL","FUTURISTIC","LUXURY","MINIMAL"],moods=["cinematic","dreamlike","precise","energetic","quiet"],cameras=["wide angle","close-up","isometric","low angle","editorial"] as const;const index=Math.floor(Math.random()*presets.length);const nextPreset=presets[index],nextMood=moods[(index+2)%moods.length],nextCamera=cameras[(index+3)%cameras.length];setPreset(nextPreset);setMood(nextMood);setCamera(nextCamera);setPrompt(`${idea.trim()}, ${nextPreset.toLowerCase()} ${category.toLowerCase()}, ${style} style, ${nextMood} mood, ${lighting}, ${nextCamera} composition, aspect ratio ${ratio}. Environment with layered depth, clear visual hierarchy and purposeful negative space.`);toast(t("common.remix"))};
  const negative=`low quality, blurry, oversaturated, cluttered composition, illegible text, watermark, duplicated objects, distorted anatomy, cheap cyberpunk clichés`;
  const save=(type:LibraryType,name:string,data:unknown)=>{try{saveLibraryItem(type,name,data);toast(t("common.saved"));window.dispatchEvent(new Event("nexus-core-save"))}catch{toast("STORAGE LIMIT REACHED","error")}};
  const smartRandom=()=>{setGHistory(h=>[...h,[g1,g2,g3,angle,gradientType]]);const base=Math.floor(Math.random()*360);setG1(hslHex(base,82,58));setG2(hslHex((base+45+Math.random()*35)%360,78,52));setG3(hslHex((base+170+Math.random()*50)%360,72,58));setAngle(Math.floor(Math.random()*360));setGFuture([]);toast(t("common.randomized"))};
  const randomPalette=()=>{const base=Math.random()*360;const steps:Record<string,number[]>={ANALOGOUS:[-35,-15,0,18,38],COMPLEMENTARY:[0,12,180,192,210],TRIADIC:[0,120,240,260,100],SPLIT:[0,150,210,225,135],MONOCHROME:[0,0,0,0,0],NEON:[0,55,125,190,260],PASTEL:[0,40,90,160,230],"DARK UI":[0,15,190,220,260]};setPalette(palette.map((c,i)=>locks[i]?c:hslHex((base+steps[scheme][i])%360,scheme==="PASTEL"?55:78,scheme==="DARK UI"?18+i*8:scheme==="MONOCHROME"?18+i*15:52+i*4)))};
  const currentData=()=>active==="PROMPT"?{prompt,idea,category,promptMode,preset,negative}:active==="GRADIENT"?{g1,g2,g3,angle,gradientType,intensity,noise,speed,css:gradientCss}:active==="NEON"?{neonText,neonColor,outerColor,glow,blur,spread,neonSize,letter,flicker,pulse,css:neonCss}:active==="GLASS"?{opacity,glassBlur,saturation,border,borderWidth,radius,glassGlow,glassNoise,css:glassCss}:active==="COLOR"?{scheme,palette}: {motion,motionCategory,duration,delay,easing,iterations,css:motionCss};
  const sendToCode=()=>{const data=currentData();const css=active==="GRADIENT"?`.nexus-gradient { ${gradientCss.replaceAll("\n","")} }`:active==="NEON"?`.nexus-neon { ${neonCss} }`:active==="GLASS"?`.nexus-glass { ${glassCss} }`:active==="COLOR"?`:root { --nexus-bg:${palette[0]}; --nexus-surface:${palette[1]}; --nexus-primary:${palette[2]}; --nexus-secondary:${palette[3]}; --nexus-text:${palette[4]}; }`:active==="MOTION"?`.nexus-motion { ${motionCss} }`:undefined;localStorage.setItem("nexus-code-transfer",JSON.stringify({name:`${active} LAB`,data,css}));location.href="/code?transfer=1"};
  const undoGradient=()=>{const previous=gHistory.at(-1);if(!previous)return;setGFuture(f=>[[g1,g2,g3,angle,gradientType],...f]);setGHistory(h=>h.slice(0,-1));setG1(previous[0]);setG2(previous[1]);setG3(previous[2]);setAngle(previous[3]);setGradientType(previous[4])};
  const redoGradient=()=>{const next=gFuture[0];if(!next)return;setGHistory(h=>[...h,[g1,g2,g3,angle,gradientType]]);setGFuture(f=>f.slice(1));setG1(next[0]);setG2(next[1]);setG3(next[2]);setAngle(next[3]);setGradientType(next[4])};
  const saveCurrent=()=>save((active==="COLOR"?"palette":active.toLowerCase()) as LibraryType,`${active} SYSTEM`,currentData());
  useEffect(()=>{const timer=setTimeout(()=>{
    const q=new URLSearchParams(location.search);const tool=q.get("tool")?.toUpperCase() as Lab|undefined;if(tool&&labs.includes(tool))setActive(tool);
    const remix=q.get("remix");if(remix==="purple-void"){setActive("GRADIENT");setG1("#200044");setG2("#a45cff")}if(remix==="neon-tokyo"){setActive("NEON");setNeonText("TOKYO");setNeonColor("#ff45c8")}
    const library=q.get("library");if(library){const item=getLibrary().find(x=>x.id===library);if(item){const lab=(item.type==="palette"?"COLOR":item.type.toUpperCase()) as Lab;setActive(lab);const data=item.data&&typeof item.data==="object"?item.data as Record<string,unknown>:{};const text=(key:string)=>typeof data[key]==="string"?data[key] as string:null;const number=(key:string)=>typeof data[key]==="number"?data[key] as number:null;const bool=(key:string)=>typeof data[key]==="boolean"?data[key] as boolean:null;
      if(lab==="PROMPT"){if(text("prompt"))setPrompt(text("prompt")!);if(text("idea"))setIdea(text("idea")!);if(text("category"))setCategory(text("category")!);if(text("promptMode"))setPromptMode(text("promptMode")!);if(text("preset"))setPreset(text("preset")!)}
      if(lab==="GRADIENT"){if(text("g1"))setG1(text("g1")!);if(text("g2"))setG2(text("g2")!);if(text("g3"))setG3(text("g3")!);if(number("angle")!==null)setAngle(number("angle")!);if(text("gradientType"))setGradientType(text("gradientType")!);if(number("intensity")!==null)setIntensity(number("intensity")!);if(number("noise")!==null)setNoise(number("noise")!);if(number("speed")!==null)setSpeed(number("speed")!)}
      if(lab==="NEON"){if(text("neonText"))setNeonText(text("neonText")!);if(text("neonColor"))setNeonColor(text("neonColor")!);if(text("outerColor"))setOuterColor(text("outerColor")!);if(number("glow")!==null)setGlow(number("glow")!);if(number("blur")!==null)setBlur(number("blur")!);if(number("spread")!==null)setSpread(number("spread")!);if(number("neonSize")!==null)setNeonSize(number("neonSize")!);if(number("letter")!==null)setLetter(number("letter")!);if(bool("flicker")!==null)setFlicker(bool("flicker")!);if(bool("pulse")!==null)setPulse(bool("pulse")!)}
      if(lab==="GLASS"){if(number("opacity")!==null)setOpacity(number("opacity")!);if(number("glassBlur")!==null)setGlassBlur(number("glassBlur")!);if(number("saturation")!==null)setSaturation(number("saturation")!);if(number("border")!==null)setBorder(number("border")!);if(number("borderWidth")!==null)setBorderWidth(number("borderWidth")!);if(number("radius")!==null)setRadius(number("radius")!);if(number("glassGlow")!==null)setGlassGlow(number("glassGlow")!);if(number("glassNoise")!==null)setGlassNoise(number("glassNoise")!)}
      if(lab==="COLOR"){if(text("scheme"))setScheme(text("scheme")!);if(Array.isArray(data.palette)&&data.palette.every(value=>typeof value==="string"))setPalette(data.palette as string[])}
      if(lab==="MOTION"){if(text("motion"))setMotion(text("motion")!);if(text("motionCategory"))setMotionCategory(text("motionCategory")!);if(number("duration")!==null)setDuration(number("duration")!);if(number("delay")!==null)setDelay(number("delay")!);if(text("easing"))setEasing(text("easing")!);if(number("iterations")!==null)setIterations(number("iterations")!)}
    }}
    const queryIdea=q.get("idea");if(queryIdea){setIdea(queryIdea);setActive("PROMPT")}let recent:Array<{tool:string;time:string}>=[];try{recent=JSON.parse(localStorage.getItem("nexus-recent")||"[]")}catch{recent=[]}localStorage.setItem("nexus-recent",JSON.stringify([{tool:`${tool||"PROMPT"} LAB`,time:"just now"},...recent].slice(0,6)))
  },0);return()=>clearTimeout(timer)},[]);
  useEffect(()=>{const saveHandler=()=>saveCurrent();const randomHandler=()=>{if(active==="GRADIENT")smartRandom();if(active==="COLOR")randomPalette()};window.addEventListener("nexus-save",saveHandler);window.addEventListener("nexus-random",randomHandler);return()=>{window.removeEventListener("nexus-save",saveHandler);window.removeEventListener("nexus-random",randomHandler)}});
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape")setFullscreen(false);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"&&!e.shiftKey&&active==="GRADIENT"){e.preventDefault();undoGradient()}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==="z"&&active==="GRADIENT"){e.preventDefault();redoGradient()}};addEventListener("keydown",close);return()=>removeEventListener("keydown",close)});
  return <NexusShell><main className={`tools-page ${fullscreen?"preview-fullscreen":""}`}><section className="subpage-hero tools-v2-hero"><span>01 / CREATIVE SYSTEMS</span><h1>TOOL<br/><em>WORKSPACE.</em></h1><p>Controls. Live preview. Production-ready output.<br/>Save, remix and send any system directly into Code Lab.</p></section><section className="tool-workspace v2-workspace"><aside className="tool-tabs">{labs.map((lab,i)=><button className={active===lab?"active":""} onClick={()=>setActive(lab)} key={lab}><span>0{i+1}</span>{lab} LAB</button>)}</aside><div className="tool-panel"><div className="workspace-toolbar"><span>{active} LAB / ACTIVE</span><div><button onClick={undoGradient} disabled={!gHistory.length}>UNDO</button><button onClick={redoGradient} disabled={!gFuture.length}>REDO</button><button onClick={()=>setFullscreen(true)}>FULLSCREEN</button><button data-cursor="SAVE" onClick={saveCurrent}>SAVE</button><button className="send-code" data-cursor="CODE" onClick={sendToCode}>SEND TO CODE ↗</button></div></div>
  {active==="PROMPT"&&<section className="generator"><div className="generator-head"><span>01 / PROMPT LAB 2.0</span><h2>IDEA → DIRECTION</h2></div><div className="generator-grid tri-grid"><div className="controls"><label className="control"><span>CATEGORY</span><select value={category} onChange={e=>setCategory(e.target.value)}>{["IMAGE","VIDEO","WEBSITE","UI","TEXT","BRANDING","3D","PRODUCT"].map(x=><option key={x}>{x}</option>)}</select></label><Segments values={["SIMPLE","DETAILED","ULTRA"]} value={promptMode} onChange={setPromptMode}/><label className="control"><span>YOUR IDEA</span><textarea value={idea} onChange={e=>setIdea(e.target.value)}/></label><label className="control"><span>STYLE</span><input value={style} onChange={e=>setStyle(e.target.value)}/></label><label className="control"><span>MOOD</span><input value={mood} onChange={e=>setMood(e.target.value)}/></label><label className="control"><span>LIGHTING</span><input value={lighting} onChange={e=>setLighting(e.target.value)}/></label><label className="control"><span>CAMERA</span><input value={camera} onChange={e=>setCamera(e.target.value)}/></label><label className="control"><span>ASPECT RATIO</span><select value={ratio} onChange={e=>setRatio(e.target.value)}>{["1:1","4:5","16:9","9:16","21:9"].map(x=><option key={x}>{x}</option>)}</select></label><div className="preset-row">{["CINEMATIC","CYBERPUNK","MINIMAL","LUXURY","EDITORIAL","FUTURISTIC","PRODUCT","PHOTOREAL","ANIME","3D"].map(x=><button className={preset===x?"active":""} onClick={()=>setPreset(x)} key={x}>{x}</button>)}</div><button className="generate-btn" onClick={promptOutput}>ENHANCE PROMPT ↗</button><button className="save-btn" onClick={remixPrompt}>REMIX DIRECTION ↻</button></div><div className="prompt-preview tool-preview"><span>{category} / {promptMode}</span><strong>{idea||"YOUR IDEA"}</strong><i>{preset}</i></div><div className="tool-output"><span>OUTPUT / PROMPT</span><p>{prompt}</p><span>NEGATIVE PROMPT</span><small>{negative}</small><div><button onClick={()=>copy(prompt)}>COPY PROMPT</button><button onClick={()=>copy(negative)}>COPY NEGATIVE</button><button onClick={remixPrompt}>REMIX</button><button onClick={saveCurrent}>SAVE</button></div></div></div></section>}
  {active==="GRADIENT"&&<section className="generator"><div className="generator-head"><span>02 / GRADIENT LAB 2.0</span><h2>ENGINEER LIGHT.</h2></div><div className="generator-grid tri-grid"><div className="controls"><Segments values={["LINEAR","RADIAL","CONIC","MESH","AURORA"]} value={gradientType} onChange={setGradientType}/><div className="color-stack">{[[g1,setG1],[g2,setG2],[g3,setG3]].map(([value,set],i)=><label key={i}>COLOR {i+1}<input type="color" value={value as string} onChange={e=>(set as (v:string)=>void)(e.target.value)}/><b>{value as string}</b></label>)}</div><Range label="ROTATION" value={angle} min={0} max={360} onChange={setAngle} suffix="°"/><Range label="INTENSITY" value={intensity} min={40} max={180} onChange={setIntensity} suffix="%"/><Range label="NOISE" value={noise} min={0} max={30} onChange={setNoise} suffix="%"/><Range label="SPEED" value={speed} min={2} max={20} onChange={setSpeed} suffix="s"/><button className="generate-btn" onClick={smartRandom}>SMART RANDOM ↻</button></div><div className="gradient-preview tool-preview" style={{background:gradient,filter:`saturate(${intensity}%)`}}><div className="noise-layer" style={{opacity:noise/100}}/></div><div className="tool-output"><span>OUTPUT / CSS</span><code>{gradientCss}</code><div><button onClick={()=>copy(gradientCss)}>COPY CSS</button><button onClick={saveCurrent}>SAVE</button></div></div></div></section>}
  {active==="NEON"&&<section className="generator"><div className="generator-head"><span>03 / NEON LAB 2.0</span><h2>TYPE AS ENERGY.</h2></div><div className="generator-grid tri-grid"><div className="controls"><label className="control"><span>TEXT</span><input value={neonText} onChange={e=>setNeonText(e.target.value.slice(0,18))}/></label><div className="preset-row">{[["TOKYO","#ff45c8","#8b5cff"],["LASER BLUE","#64efff","#2447ff"],["CYBER PINK","#ff4fbd","#8b5cff"],["TOXIC","#b6ff35","#00d9ff"],["ULTRAVIOLET","#9b6cff","#ff4fbd"],["ICE","#eaffff","#64efff"],["RED ALERT","#ff354f","#ff7a00"]].map(([n,c,o])=><button key={n} onClick={()=>{setNeonColor(c);setOuterColor(o)}}>{n}</button>)}</div><div className="color-stack"><label>CORE COLOR<input type="color" value={neonColor} onChange={e=>setNeonColor(e.target.value)}/></label><label>OUTER GLOW<input type="color" value={outerColor} onChange={e=>setOuterColor(e.target.value)}/></label></div><Range label="GLOW" value={glow} min={0} max={100} onChange={setGlow}/><Range label="BLUR" value={blur} min={0} max={30} onChange={setBlur}/><Range label="SPREAD" value={spread} min={0} max={12} onChange={setSpread}/><Range label="TEXT SIZE" value={neonSize} min={32} max={150} onChange={setNeonSize}/><Range label="LETTER SPACING" value={letter} min={0} max={20} onChange={setLetter}/><label className="toggle"><input type="checkbox" checked={flicker} onChange={e=>setFlicker(e.target.checked)}/><i/><span>FLICKER</span></label><label className="toggle"><input type="checkbox" checked={pulse} onChange={e=>setPulse(e.target.checked)}/><i/><span>PULSE</span></label></div><div className="neon-preview tool-preview"><strong className={`${flicker?"flicker":""} ${pulse?"demo-pulse":""}`} style={{color:neonColor,fontSize:neonSize,letterSpacing:letter,textShadow:`0 0 ${spread}px #fff,0 0 ${blur}px ${neonColor},0 0 ${glow}px ${neonColor},0 0 ${glow*2}px ${outerColor}`}}>{neonText}</strong></div><div className="tool-output"><span>OUTPUT / CSS + HTML</span><code>{neonCss}</code><code>{`<span class="nexus-neon">${neonText}</span>`}</code><div><button onClick={()=>copy(neonCss)}>COPY CSS</button><button onClick={()=>copy(`<span class="nexus-neon">${neonText}</span>`)}>COPY HTML</button><button onClick={saveCurrent}>SAVE</button></div></div></div></section>}
  {active==="GLASS"&&<section className="generator"><div className="generator-head"><span>04 / GLASS LAB 2.0</span><h2>SHAPE TRANSPARENCY.</h2></div><div className="generator-grid tri-grid"><div className="controls"><Range label="BACKGROUND OPACITY" value={opacity} min={1} max={35} onChange={setOpacity}/><Range label="BLUR" value={glassBlur} min={0} max={60} onChange={setGlassBlur}/><Range label="SATURATION" value={saturation} min={50} max={200} onChange={setSaturation}/><Range label="BORDER OPACITY" value={border} min={0} max={50} onChange={setBorder}/><Range label="BORDER WIDTH" value={borderWidth} min={0} max={6} onChange={setBorderWidth}/><Range label="RADIUS" value={radius} min={0} max={60} onChange={setRadius}/><Range label="GLOW" value={glassGlow} min={0} max={80} onChange={setGlassGlow}/><Range label="NOISE" value={glassNoise} min={0} max={30} onChange={setGlassNoise}/></div><div className="glass-preview tool-preview"><div className="glass-aurora"/><div className="glass-card" style={{background:`rgba(255,255,255,${opacity/100})`,backdropFilter:`blur(${glassBlur}px) saturate(${saturation}%)`,border:`${borderWidth}px solid rgba(255,255,255,${border/100})`,borderRadius:radius,boxShadow:`0 0 ${glassGlow}px rgba(101,234,255,.16)`}}><span>NEXUS SURFACE</span><strong>DIGITAL<br/>MATTER.</strong><p>Complex light reveals the glass.</p></div></div><div className="tool-output"><span>OUTPUT / CSS</span><code>{glassCss}</code><div><button onClick={()=>copy(glassCss)}>COPY CSS</button><button onClick={saveCurrent}>SAVE</button></div></div></div></section>}
  {active==="COLOR"&&<section className="generator"><div className="generator-head"><span>05 / COLOR LAB 2.0</span><h2>FIND A FREQUENCY.</h2></div><Segments values={["ANALOGOUS","COMPLEMENTARY","TRIADIC","SPLIT","MONOCHROME","NEON","PASTEL","DARK UI"]} value={scheme} onChange={setScheme}/><div className="palette-preview">{palette.map((color,i)=><div key={i} className="palette-color" style={{background:color,color:i<2?"#fff":"#050509"}}><button onClick={()=>{const next=[...locks];next[i]=!next[i];setLocks(next)}}>{locks[i]?"🔒 LOCKED":"LOCK"}</button><strong>{color}</strong><button onClick={()=>copy(color)}>COPY HEX</button></div>)}</div><div className="contrast-panel"><span>ACCESSIBILITY CHECK</span><strong>{contrast(palette[0],palette[4]).toFixed(1)}:1</strong><b>{contrast(palette[0],palette[4])>=7?"AAA":contrast(palette[0],palette[4])>=4.5?"AA":"FAIL"}</b><p>{contrast(palette[0],palette[4])>=4.5?"Suitable for text and background.":"Use for decorative elements, not body text."}</p></div><div className="palette-actions"><button className="generate-btn" onClick={randomPalette}>SMART RANDOM ↻</button><button className="save-btn" onClick={saveCurrent}>SAVE PALETTE</button></div></section>}
  {active==="MOTION"&&<section className="generator"><div className="generator-head"><span>06 / MOTION LAB 2.0</span><h2>MAKE IT MOVE.</h2></div><div className="generator-grid tri-grid"><div className="controls"><Segments values={["ENTRANCE","EXIT","HOVER","LOOP","TEXT","BUTTON","CARD","BACKGROUND"]} value={motionCategory} onChange={setMotionCategory}/><div className="motion-picker">{["reveal","fade","scale","blur","glitch","float","pulse","magnetic"].map(x=><button className={motion===x?"active":""} key={x} onClick={()=>setMotion(x)}>{x.toUpperCase()}</button>)}</div><Range label="DURATION" value={duration} min={100} max={3000} onChange={setDuration} suffix="ms"/><Range label="DELAY" value={delay} min={0} max={2000} onChange={setDelay} suffix="ms"/><Range label="ITERATIONS" value={iterations} min={1} max={9} onChange={setIterations} suffix={iterations===9?" ∞":""}/><Segments values={["LINEAR","EASE","EASE IN","EASE OUT","EASE IN OUT","SPRING"]} value={easing} onChange={setEasing}/><div className="timeline-controls"><button onClick={()=>setPlaying(true)}>PLAY</button><button onClick={()=>setPlaying(false)}>PAUSE</button><button onClick={()=>{setMotionKey(k=>k+1);setPlaying(true)}}>RESTART</button></div><div className={`easing-graph easing-${easing.toLowerCase().replaceAll(" ","-")}`}><i/></div></div><div className="motion-stage tool-preview" key={motionKey}><div className={`motion-object ${playing?`demo-${motion}`:"paused"}`} style={{animationDuration:`${duration}ms`,animationDelay:`${delay}ms`,animationIterationCount:iterations===9?"infinite":iterations}}><i/><strong>NEXUS</strong><span>{motionCategory} / {motion.toUpperCase()}</span></div></div><div className="tool-output"><span>OUTPUT / CSS</span><code>{motionCss}</code><div><button onClick={()=>copy(motionCss)}>COPY CSS</button><button onClick={saveCurrent}>SAVE</button></div></div></div></section>}
  </div></section><div className="mobile-tool-toolbar"><button onClick={()=>document.querySelector(".controls")?.scrollIntoView()}>EDIT</button><button onClick={()=>{setOutputTab("preview");document.querySelector(".tool-preview")?.scrollIntoView()}}>PREVIEW</button><button onClick={()=>{setOutputTab("code");document.querySelector(".tool-output")?.scrollIntoView()}}>CODE</button><button onClick={saveCurrent}>SAVE</button></div>{fullscreen&&<div className="fullscreen-preview"><button onClick={()=>setFullscreen(false)}>ESC / CLOSE</button><div style={{background:active==="GRADIENT"?gradient:undefined}}>{active==="NEON"?<strong style={{color:neonColor,textShadow:`0 0 ${glow}px ${neonColor}`,fontSize:neonSize}}>{neonText}</strong>:active==="MOTION"?<div className={`motion-object demo-${motion}`}><strong>NEXUS</strong></div>:<h2>{active} / LIVE PREVIEW</h2>}</div></div>}</main></NexusShell>;
}
